config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('entry_form.urls')),
]

entry_form/urls.py
from django.urls import path
from . import views

app_name = 'entry_form'
urlpatterns = [
    path('', views.begin_entry_view, name="begin-template"),
    path('entry-form/', views.entry_form_view , name="form-template"),
    path('unexpected-error/', views.unexpected_error_view),
    path('submission-confirmation-<int:pk>/', views.submission_confirmation, name="submission"),
]

entry_form/models.py
from django.db import models
from . import constants
from django.core.validators import (
    RegexValidator,
    MaxValueValidator,
)


class MailingAddress(models.Model):
    in_Care_Of = models.CharField(max_length=33, blank=True)
    address_Line_1 = models.CharField(max_length=33)
    address_Line_2 = models.CharField(max_length=33, blank=True)
    city = models.CharField("City/Town", max_length=33)
    province = models.CharField("District/County/Province/State", max_length=33)
    zip_Code = models.CharField("Postal Code/Zip Code", max_length=33, blank=True)
    country = models.CharField(max_length=40, choices=constants.COUNTRY_CHOICES)


class Entrant(models.Model):
    last_Name = models.CharField("Last/Family Name", max_length=33, validators=[RegexValidator(regex="[a-zA-Z`\s\-]+")])
    first_Name = models.CharField(max_length=33, validators=[RegexValidator(regex="[a-zA-Z`\s\-]+")], blank=True)
    middle_Name = models.CharField(max_length=33, validators=[RegexValidator(regex="[a-zA-Z`\s\-]+")], blank=True)
    gender = models.CharField(max_length=6, choices=constants.GENDER_CHOICES)
    birth_Date = models.DateField()
    birth_City = models.CharField(max_length=33, blank=True)
    birth_Country = models.CharField(max_length=40, choices=constants.COUNTRY_CHOICES)
    eligibility_Country = models.CharField(max_length=40, choices=constants.COUNTRY_CHOICES, blank=True)
    entrant_Photograph = models.ImageField()
    mailing_Address = models.OneToOneField(MailingAddress, on_delete=models.CASCADE)
    residence_Country = models.CharField(max_length=40, choices=constants.COUNTRY_CHOICES)
    phone_Number = models.CharField(max_length=33, blank=True)
    email_Address = models.EmailField("E-Mail Address")
    education_Level = models.CharField(max_length=33, choices=constants.EDUCATION_LEVEL_CHOICES)
    marital_Status = models.CharField(max_length=85, choices=constants.MARITAL_STATUS_CHOICES)
    children_Number = models.PositiveSmallIntegerField(validators=[MaxValueValidator(20)])
    entry_Datetime = models.DateTimeField(auto_now_add=True)
    confirmation_Number = models.CharField(max_length=16, unique=True)
    digital_Signature = models.CharField(max_length=40, unique=True)

entry_form/forms.py
from django import forms
from django.core.validators import FileExtensionValidator
from django.core.exceptions import ValidationError
from . import models


def photograph_validation(fileObj):
    if fileObj.size > 240 * 1024:
        raise ValidationError("An unexpected error occured.")
    elif fileObj.content_type != "image/jpeg":
        raise ValidationError("An unexpected error occured.")


class MailingAddressForm(forms.ModelForm):
    class Meta:
        model = models.MailingAddress
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['in_Care_Of'].widget.attrs.update({'class': 'form-control width-60'})
        self.fields['address_Line_1'].widget.attrs.update({'class': 'form-control width-60'})
        self.fields['address_Line_2'].widget.attrs.update({'class': 'form-control width-60'})
        self.fields['city'].widget.attrs.update({'class': 'form-control width-60'})
        self.fields['province'].widget.attrs.update({'class': 'form-control width-60'})
        self.fields['zip_Code'].widget.attrs.update({'class': 'form-control width-60'})
        self.fields['country'].widget.attrs.update({'class': 'form-select width-60'})


class EntrantForm(forms.ModelForm):
    birth_month = forms.IntegerField(label="Month", min_value=1, max_value=12)
    birth_day = forms.IntegerField(label="Day", min_value=1, max_value=31)
    birth_year = forms.IntegerField(label="Year", min_value=1907, max_value=2012)

    birth_month.widget.attrs.update({'class': "form-control", 'placeholder': "mm"})
    birth_day.widget.attrs.update({'class': "form-control", 'placeholder': "dd"})
    birth_year.widget.attrs.update({'class': "form-control", 'placeholder': "yyyy"})

    class Meta:
        model = models.Entrant
        exclude = [
            "mailing_Address",
            "birth_Date",
            "confirmation_Number",
            "digital_Signature",
            "entry_Datetime",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['last_Name'].widget.attrs.update({'class': 'form-control'})
        self.fields['first_Name'].widget.attrs.update({'class': 'form-control'})
        self.fields['middle_Name'].widget.attrs.update({'class': 'form-control'})
        self.fields['birth_City'].widget.attrs.update({'class': 'form-control width-60'})
        self.fields['birth_Country'].widget.attrs.update({'class': 'form-select width-60'})
        self.fields['eligibility_Country'].widget.attrs.update({'class': 'form-select width-60', 'disabled': 'disabled'})
        self.fields['entrant_Photograph'].widget.attrs.update({'class': 'd-none', "accept": "image/jpeg"})
        self.fields['entrant_Photograph'].validators.append(FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'jfif', 'pjpeg', 'pjp']))
        self.fields['entrant_Photograph'].validators.append(photograph_validation)
        self.fields['residence_Country'].widget.attrs.update({'class': 'form-select width-60'})
        self.fields['phone_Number'].widget.attrs.update({'class': 'form-control width-60'})
        self.fields['email_Address'].widget.attrs.update({'class': 'form-control width-60'})
        self.fields['children_Number'].widget.attrs.update({'class': 'form-control width-25', "max": 20})

entry_form/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Entrant
from .forms import MailingAddressForm, EntrantForm
import datetime
import string
from random import choice
from django.core.exceptions import BadRequest
from django.urls import reverse


def begin_entry_view(request): 
    return render(request, 'entry_form/begin_entry.html')


def generator(len):
    characters = string.ascii_uppercase + string.digits
    generated = [choice(characters) for i in range(len)]
    generated_value = "".join(generated)
    if Entrant.objects.filter(confirmation_Number=generated_value) or Entrant.objects.filter(digital_Signature=generated_value):
        generator(len)
    else:
        return generated_value


def entry_form_view(request):
    if request.method == 'POST':
        mailing_address_form = MailingAddressForm(request.POST)
        entrant_form = EntrantForm(request.POST, request.FILES)
        if mailing_address_form.is_valid() and entrant_form.is_valid():
            entrant_birth_date = datetime.date(
                entrant_form.cleaned_data["birth_year"],
                entrant_form.cleaned_data["birth_month"],
                entrant_form.cleaned_data["birth_day"]
            )
            entrant_confirmation_number = "202X" + generator(12)
            entrant_digital_signature = generator(40)
            if not entrant_form.cleaned_data.get('eligibility_country'):
                entrant_form.cleaned_data['eligibility_country'] = entrant_form.cleaned_data['birth_Country']
            
            mailing_address_instance = mailing_address_form.save()

            entrant = entrant_form.save(commit=False)
            entrant.birth_Date = entrant_birth_date
            entrant.mailing_Address = mailing_address_instance
            entrant.confirmation_Number = entrant_confirmation_number
            entrant.digital_Signature = entrant_digital_signature
            entrant.save()
            entrant_pk = entrant.pk

            return HttpResponseRedirect(reverse('entry_form:submission', args=[entrant_pk]))
        raise BadRequest
    mailing_address_form = MailingAddressForm()
    entrant_form = EntrantForm()
    context = {
        "mailing_address_form": mailing_address_form,
        "entrant_form": entrant_form,
    }
    return render(request, 'entry_form/entry_form.html', context)


def submission_confirmation(request, pk):
    entrant_info = Entrant.objects.get(pk=pk)
    context = {
        'last_name': entrant_info.last_Name,
        'first_name': entrant_info.first_Name,
        'middle_name': entrant_info.middle_Name,
        'confirmation_number': entrant_info.confirmation_Number,
        'birth_year': entrant_info.birth_Date.year,
        'digital_signature': entrant_info.digital_Signature,
        'entry_datetime': entrant_info.entry_Datetime,
    }
    return render(request, "entry_form/submission_confirmation.html", context)


def unexpected_error_view(request):
    return render(request, "entry_form/unexpected_error.html")

entry_form/templates/entry_form/begin_entry.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'entry_form/style.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <div class="card rounded-1 mb-4 text-center">
      <div class="card-header fw-medium head-color">
        Entry Form
      </div>

      <div class="card-body p-4">
        <p>The entry form is prepared in two parts, one for the primary Entrant and one for derivatives (if any). Each part must be completed correctly and completely before going to the next part. After all parts are completed, the entry will be submitted to the DV-202X Processing Center. Click the link below to begin the entry process.</p>
        <a href="{% url 'entry_form:form-template' %}" class="btn btn-success bg-gradient">Begin Entry</a>
      </div>
    </div>
  </div>
{% endblock %}

entry_form/templates/entry_form/submission_confirmation.html
{% extends "base.html" %}

{% block body %}
  <div class="container mt-5">
    <div class="text-center mb-4">
      <h4>DV-202X Submission Confirmation: Entry Received</h4>
    </div>

    <div class="fw-medium bg-success bg-gradient text-center mb-3 p-2">
      <span class="fs-3">Success!</span>
    </div>

    <div>
      <p class="text-center">Your entry for the 202X Diversity Visa program was received on {{ entry_datetime|date:"l, F j, Y" }} at {{ entry_datetime|time:"g:i:s A T" }}. Please do <b>NOT</b> close this window until you have printed this confirmation page or made a record of your Confirmation Number.</p>
      <div class="row my-4">
        <div class="col">
          <div><b>Entrant Name:</b></div>
          <div><b>Confirmation Number:</b></div>
          <div><b>Year of Birth:</b></div>
          <div><b>Digital Signature:</b></div>
        </div>
        <div class="col">
          <div>{{ last_name }}{% if middle_name or first_name%},{% endif %} {{ middle_name }} {{ first_name }}</div>
          <div>{{ confirmation_number }}</div>
          <div>{{ birth_year }}</div>
          <div>{{ digital_signature }}</div>
        </div>
        <div class="col"></div>
        <div class="col"></div>
      </div>
      <p>Thank you for your entry for the 202X Diversity Visa Program.</p>
      <p><b>Please either print this page or make a record of the confirmation number before closing this window. You will not be able to retrieve thisnumber after you close this window.</b></p>
      <p>You must retain your confirmation number in order to check your entry status via <a href="" target="_blank">Entrant Status Check</a> between May 3, 202X-1 and September 30, 202X todetermine whether your entry was selected for further processing in the 202X Diversity Visa Program. You will be <b>REQUIRED</b> to enter your confirmationnumber in combination with other personal information in order to check on your entry status.</p>
      <p><b>Selectees will not receive selectee notifications or letters by regular postal mail from the Kentucky Consular Center (KCC).</b></p>
      <p><b>Do not submit additional Entry Forms with this person as the Primary Entrant! Multiple entries will disqualify the Entrant from participation inthe 202X Diversity Visa Program.</b></p>
    </div>
  </div>
{% endblock %}

entry_form/templates/entry_form/unexpected_error.html
{% extends "base.html" %}

{% block body %}
  <div class="d-flex justify-content-center align-items-center" style="height: 87vh;">
    <div class="text-center bg-warning p-4 border border-black border-3">
      <h1 class="">An unexpected error occured.</h1>
      <h4>Please submit a new application.</h4>
      <div class="mt-3">
        <a href="{% url 'entry_form:form-template' %}" class="btn btn-success bg-gradient">Begin Entry</a>
      </div>
    </div>
  </div>
{% endblock %}